service: validation-onboarding

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  stage: dev
  memorySize: 1024

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    layers:
      - arn:aws:lambda:us-east-2:315068324448:layer:libs_python:8

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**